DROP TABLE IF EXISTS elvls;
DROP TABLE IF EXISTS history;

CREATE TABLE elvls
(
    isin  VARCHAR(12) PRIMARY KEY,
    value BIGINT NOT NULL
);

CREATE TABLE history
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    isin VARCHAR(12) NOT NULL,
    bid  BIGINT,
    ask  BIGINT      NOT NULL,
    date DATETIME    NOT NULL
);